### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by nubovik01** [rldv1/SCRE1_API_CLIENT#1]

**Comment by rldv1** [comment]
![изображение](https://github.com/rldv1/SCRE1_API_CLIENT/assets/118821863/67dfcf66-a2c9-42e9-91a1-c569da922faa)
![aA3GVYg_460s](https://github.com/rldv1/SCRE1_API_CLIENT/assets/118821863/34925508-416b-4892-b57b-710b87bea947)

**Comment by nubovik01** [comment]
![image](https://github.com/rldv1/SCRE1_API_CLIENT/assets/50026919/8d09b33e-5808-446d-a01b-236d4fdcd440)
